src/Entity/Distribucion.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * Distribucion
 *
 * @ORM\Table(name="distribucion")
 * @ORM\Entity(repositoryClass="App\Repository\DistribucionRepository")
 */
class Distribucion
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Palets", inversedBy="distribucion")
     * @ORM\JoinColumn(nullable=true)
     */
    private $palets;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Recepcion", inversedBy="distribucion")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recepcion;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Seccion", inversedBy="distribucion")
     * @ORM\JoinColumn(nullable=false)
     */
    private $secciones;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Despachos", mappedBy="distribucion")
     */
    private $despachos;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $disNumLote;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $codigo_gar;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $modelo;

    /**
     * @ORM\Column(type="datetime")
     */
    private $disFecDistribucion;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $disFecDespacho;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $disEstado;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $disRucFactura;

    /**
     * @ORM\Column(type="integer", length=1, nullable=true)
     */
    private $disStatus;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $disSecOrigen;

    public function __toString()
    {
        return $this->codigo_gar;
    }

    public function __construct()
    {
        $this->despachos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDisNumLote(): ?string
    {
        return $this->disNumLote;
    }

    public function setDisNumLote(string $disNumLote): self
    {
        $this->disNumLote = $disNumLote;

        return $this;
    }

    public function getCodigoGar(): ?string
    {
        return $this->codigo_gar;
    }

    public function setCodigoGar(string $codigo_gar): self
    {
        $this->codigo_gar = $codigo_gar;

        return $this;
    }

    public function getDisFecDistribucion(): ?\DateTimeInterface
    {
        return $this->disFecDistribucion;
    }

    public function setDisFecDistribucion(\DateTimeInterface $disFecDistribucion): self
    {
        $this->disFecDistribucion = $disFecDistribucion;

        return $this;
    }

    public function getDisFecDespacho(): ?\DateTimeInterface
    {
        return $this->disFecDespacho;
    }

    public function setDisFecDespacho(?\DateTimeInterface $disFecDespacho): self
    {
        $this->disFecDespacho = $disFecDespacho;

        return $this;
    }

    public function getDisEstado(): ?string
    {
        return $this->disEstado;
    }

    public function setDisEstado(string $disEstado): self
    {
        $this->disEstado = $disEstado;

        return $this;
    }

    public function getRecepcion(): ?Recepcion
    {
        return $this->recepcion;
    }

    public function setRecepcion(?Recepcion $recepcion): self
    {
        $this->recepcion = $recepcion;

        return $this;
    }

    public function getSecciones(): ?Seccion
    {
        return $this->secciones;
    }

    public function setSecciones(?Seccion $secciones): self
    {
        $this->secciones = $secciones;

        return $this;
    }

    public function getPalets(): ?Palets
    {
        return $this->palets;
    }

    public function setPalets(?Palets $palets): self
    {
        $this->palets = $palets;

        return $this;
    }

    public function getModelo(): ?string
    {
        return $this->modelo;
    }

    public function setModelo(string $modelo): self
    {
        $this->modelo = $modelo;

        return $this;
    }

    /**
     * @return Collection<int, Despachos>
     */
    public function getDespachos(): Collection
    {
        return $this->despachos;
    }

    public function addDespacho(Despachos $despacho): self
    {
        if (!$this->despachos->contains($despacho)) {
            $this->despachos[] = $despacho;
            $despacho->setDistribucion($this);
        }

        return $this;
    }

    public function removeDespacho(Despachos $despacho): self
    {
        if ($this->despachos->removeElement($despacho)) {
            // set the owning side to null (unless already changed)
            if ($despacho->getDistribucion() === $this) {
                $despacho->setDistribucion(null);
            }
        }

        return $this;
    }

    public function getDisRucFactura(): ?string
    {
        return $this->disRucFactura;
    }

    public function setDisRucFactura(?string $disRucFactura): self
    {
        $this->disRucFactura = $disRucFactura;

        return $this;
    }

    public function getDisStatus(): ?int
    {
        return $this->disStatus;
    }

    public function setDisStatus(?int $disStatus): self
    {
        $this->disStatus = $disStatus;

        return $this;
    }

    public function getDisSecOrigen(): ?int
    {
        return $this->disSecOrigen;
    }

    public function setDisSecOrigen(?int $disSecOrigen): self
    {
        $this->disSecOrigen = $disSecOrigen;

        return $this;
    }


}

src/Form/DistribucionType.php
<?php

namespace App\Form;

use App\Entity\Distribucion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class DistribucionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('disNumLote')
            ->add('codigo_gar')
            ->add('disFecDistribucion')
            ->add('disFecDespacho')
            ->add('disEstado')
            ->add('recepcion')
            ->add('secciones')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Distribucion::class,
        ]);
    }
}

src/Controller/DistribucionController.php
<?php

namespace App\Controller;

use App\Entity\Despachos;
use App\Entity\DetalleFac;
use App\Entity\Distribucion;
use App\Entity\Facturas;
use App\Form\DistribucionType;
use App\Repository\BateriasRepository;
use App\Repository\CodigosQrRepository;
use App\Repository\DespachosRepository;
use App\Repository\DetalleFacRepository;
use App\Repository\DistribucionRepository;
use App\Repository\FacturasRepository;
use App\Repository\GarantiasRepository;
use App\Repository\PaletsBateriasRepository;
use App\Repository\PaletsRepository;
use App\Repository\RecepcionRepository;
use App\Repository\SeccionRepository;
use App\Repository\UsersRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/distribucion")
 */
class DistribucionController extends AbstractController
{
    /**
     * Guarda registros de reprocesos
     *
     * @Route("/guarda-reprocesos", name="reproceso_guarda_registros", methods={"POST","GET"})
     */
    public function guardaReproceso(GarantiasRepository $garantiasRepository, BateriasRepository $bateriasRepository, EntityManagerInterface $entityManager,
                    DistribucionRepository $distribucionRepository, RecepcionRepository $recepcionRepository, CodigosQrRepository $codigosQrRepository,
                    PaletsBateriasRepository $paletsBateriasRepository)
    {

        $datos = $_POST['data'];
        $batId = $_POST['batId'];
        $bateria = $bateriasRepository->find($batId);
        //dd($datos);
        foreach ($datos as $data){
            $garantia =  $garantiasRepository->findBy(['garCodigo'=>$data['codigo_gar']])[0];
            $garantia->setBarId($batId);
            $entityManager->persist($garantia);

            $codQr = $codigosQrRepository->findBy(['codigo_gar'=>$data['codigo_gar']])[0];
            $codQr->setModelo($bateria->getBatNomProdNeural());
            $codQr->setNomProdNeural($bateria->getBatNomProdNeural());
            $codQr->setCodEstado("REPROCESADO");
            $entityManager->persist($codQr);

            $distribucion = $distribucionRepository->findBy(['codigo_gar'=>$data['codigo_gar']])[0];
            $entityManager->remove($distribucion);

            $recepcion = $recepcionRepository->findBy(['codigo_gar'=>$data['codigo_gar']])[0];
            $entityManager->remove($recepcion);

            $pallet = $paletsBateriasRepository->findBy(['codigo_gar'=>$data['codigo_gar']])[0];
            $entityManager->remove($pallet);

        }

        $entityManager->flush();
        return new Response(json_encode('ok'),200, array('Content-Type' => 'application/json'));
    }

    /** index baterias para reprocesos
     * @Route("/index-baterias-reprocesos", name="reproceso_baterias_index", methods={"GET","POST"})
     */
    public function indexReprocesosBaterias(DistribucionRepository $distribucionRepository, BateriasRepository $bateriasRepository): Response{
        return $this->render('distribucion/index_reproceso.html.twig', [
            'baterias' => $distribucionRepository->getBateriasDistribuidas(),
            'modelos' => $bateriasRepository->getByEstado(1)
        ]);
    }

    /**
     * @Route("/distribucion/remueve/facturas/{facId}/{regId}/{fecDesde}/{fecHasta}", name="distribucion_remove_facturas", methods={"GET", "POST"})
     */
    public function disRemoveFacturas($facId, $regId, $fecDesde, $fecHasta, DistribucionRepository $distribucionRepository,
                                      CodigosQrRepository $codigosQrRepository, DespachosRepository $despachosRepository, FacturasRepository $facturasRepository,
                                        DetalleFacRepository $detalleFacRepository): Response
    {
        $em = $this->getDoctrine()->getManager();
        //$datFacura = $usersRepository->getDetalleFactura($codDetFactura);
        $registros = $despachosRepository->getDespachosByCodDetFac($regId);
        //dd($registros);
        foreach ($registros as $registro){
            $des = $despachosRepository->find($registro['id']);
            $dis = $distribucionRepository->find($des->getDistribucion()->getId());
            $cod = $codigosQrRepository->findBy(['codigo_gar'=>$dis->getCodigoGar()])[0];
            $cod->setCodEstado('DISTRIBUIDO');
            $em->persist($cod);

            $dis->setDisEstado('INGRESADO');
            $dis->setDisFecDespacho(null);
            $em->persist($dis);
            $em->remove($des);
        }
        $em->flush();

        /*$registros = $usersRepository->getDetallesFactura($codfac);

        foreach ($registros as $key=>$registro){
            $existe = $despachosRepository->findBy(['codDetFac'=>$registro['coddetfac']]);
            if($existe){
                $registros[$key]['detFacEstado'] = "ASIGNADO";
            }
        }*/

        //$factura = $facturasRepository->findBy(['detalleFac'=> $regId])[0];

        //Elimina el registro en detalle de la factura
        $detalle = $detalleFacRepository->find($regId);
        if(!$detalle){

        }else{
            $detalle->setRegEstado('REGISTRADA');
            $em->persist($detalle);
            $em->flush();
        }

        $detEstado = $detalleFacRepository->findBy(['facturas'=>$facId, 'regEstado'=>['PARCIAL', 'COMPLETADO']]);
        if(count($detEstado)<1){
            $detalle->getFacturas()->setFacEstado('REGISTRADA');
        }else{
            $detalle->getFacturas()->setFacEstado('PARCIAL');
        }
        $detalle->getFacturas()->setFacFecDespacho(null);
        $em->persist($detalle);
        $em->flush();

        return $this->redirectToRoute('facturas_detalle',['facId'=>$facId, 'fecDesde'=>$fecDesde, 'fecHasta'=>$fecHasta]);

    }

    /**
     * @Route("/guarda-baterias-asignadas", name="distribucion_guarda_baterias_asignadas", methods={"POST"})
     */
    public function guardaBateriasAsignadas(DistribucionRepository $distribucionRepository, FacturasRepository $facturasRepository,
                                            CodigosQrRepository $codigosQrRepository, DespachosRepository $despachosRepository, DetalleFacRepository $detalleFacRepository): Response
    {
        //dd($_POST);
        $em = $this->getDoctrine()->getManager();
        $factura =  $facturasRepository->find($_POST['idFac']);
        $detalle = $detalleFacRepository->find($_POST['idDet']);
        $registros = json_decode($_POST['data']);
        //dd($registros);
        foreach ($registros as $registro){
            $distribucion = $distribucionRepository->find($registro->id);
            $distribucion->setDisRucFactura($factura->getCustomerNumber());
            $distribucion->setDisStatus(1);
            $em->persist($distribucion);

            $despacho = new Despachos();
            $despacho->setUsers( $this->getUser());
            $despacho->setDetalleFac($detalle);
            $despacho->setDistribucion($distribucion);
            $despacho->setCodGarantia($distribucion->getCodigoGar());
            $despacho->setNumber($factura->getNumFac());
            $despacho->setDescription($detalle->getDescription());
            $despacho->setDescription2($detalle->getDescription2());
            $despacho->setActGarantia(false);
            $em->persist($despacho);
            $distribucion->setDisEstado('DESPACHADO');
            $distribucion->setDisFecDespacho(new \DateTime('now'));
            $em->persist($distribucion);
            $codigoQr = $codigosQrRepository->findBy(['codigo_gar'=>$distribucion->getCodigoGar()])[0];
            $codigoQr->setCodEstado('DESPACHADO');
            $em->persist($codigoQr);
        }
        if(count($registros) < ($detalle->getQuantity() - $_POST['canDespachada'])){
            $detalle->setRegEstado("PARCIAL");
        }else{
            $detalle->setRegEstado("COMPLETADO");
        }
        $em->flush();
        //CAMBIA DE ESTADO A LA FACTURA
        $numDetalle = $detalleFacRepository->getByEstado($_POST['idFac']);
        //dd($detFacErp);

        //dd($bandera1);
        if (count($numDetalle)<1){
                $factura->setFacEstado('COMPLETADA');
                $factura->setFacFecDespacho(new \DateTime('now'));
        }else{
            $factura->setFacEstado('PARCIAL');
        }
        $em->persist($factura);
        $em->flush();

        return $this->redirectToRoute('facturas_detalle', ['facId'=>$_POST['idFac'], 'fecDesde'=> $_POST['fecDesde'], 'fecHasta'=>$_POST['fecHasta']], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/distribucion-agrega-facturas/{regId}/{fecDesde}/{fecHasta}", name="distribucion_add_facturas", methods={"GET"})
     */
    public function disAddFacturas($regId, $fecDesde, $fecHasta, DistribucionRepository $distribucionRepository,
                                   DetalleFacRepository $detalleFacRepository, DespachosRepository $despachosRepository): Response
    {
        $detalle = $detalleFacRepository->find($regId);
        $registros = $distribucionRepository->getBateriasByModelo($detalle->getDescription());
        $canDespachadas = $despachosRepository->findBy(['detalleFac' =>$regId]);
        return $this->render('distribucion/asigna_baterias.html.twig', [
            'registros' => $registros,
            'detalle' => $detalle,
            'fecDesde' => $fecDesde,
            'fecHasta' => $fecHasta,
            'canDespachada' => count($canDespachadas)
        ]);
    }

    /**
     * @Route("/distribucion-palets-index", name="distribucion_palets_index", methods={"GET"})
     */
    public function indexDistribucion(PaletsRepository $paletsRepository): Response
    {
        return $this->render('distribucion/index_palets.html.twig', [
            'palets' => $paletsRepository->getByEstado(['RECIBIDO', 'DISTRIBUIDO']),
        ]);
    }

    /**
     * Consulta detalle x seccion
     *

templates/distribucion/_delete_form.html.twig
<form method="post" action="{{ path('distribucion_delete', {'id': distribucion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ distribucion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/distribucion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/distribucion/asigna_baterias.html.twig
{% extends 'base.html.twig' %}

{% block title %}Asignación de Baterias{% endblock %}

{% block contenido %}
    <style>
        @media (min-width: 1200px){
            .modal-xl {
                max-width: 1568px;
            }
        }
    </style>
    <main>
    <div class="container-fluid p-0">
        <div class="row justify-content-center mt-4 ">
            <div class="col-6 text-left" style="font-size: 24px">
                <i class="fas fa-list-ul text-danger"></i><span class="text-danger"> Asignación de Baterias a Facturas</span>
            </div>
            <div class="col-2"></div>
            <div class="col-2">
            </div>
        </div>
        <hr>
        <form class="needs-validation" novalidate action="{{ path("distribucion_guarda_baterias_asignadas") }}" method="post" name="formulario" >
            <div class="row justify-content-center mt-4 ">
                <div class="col-2 text-left">
                    <label>Factura Id</label>
                    <input id="idFac" name="idFac" type="text" class="form form-control" readonly value="{{ detalle.facturas.id }}" />
                    <input id="fecDesde" name="fecDesde" type="text" style="display: none" readonly value="{{ fecDesde }}" />
                    <input id="fecHasta" name="fecHasta" type="text" style="display: none" readonly value="{{ fecHasta }}" />
                </div>
                <div class="col-2 text-left">
                    <label>Detalle Id</label>
                    <input name="idDet" type="text" class="form form-control" readonly value="{{ detalle.id }}" />
                </div>
                <div class="col-2">
                    <label>Nombre Producto (Modelo)</label>
                    <input name="nombrepro" type="text" class="form form-control" readonly value="{{ detalle.description2 }}" />
                </div>
                <div class="col-2">
                    <label>Descripción</label>
                    <input name="descprodetfac" type="text" class="form form-control" readonly value="{{ detalle.description }}" />
                </div>
                <div class="col-2">
                    <label>Cantidad Requerida</label>
                    <input id="canRequerida" name="cantdetfac" type="text" class="form form-control" readonly value="{{ detalle.quantity - canDespachada }}" />
                    <input id="canDespachada" name="canDespachada" type="text" class="form form-control" readonly value="{{ canDespachada }}" />
                </div>
                <div class="col-2">
                    <label>Cantidad Seleccionada</label>
                    <input id="canSeleccionada" name="canSeleccionada" type="text" class="form form-control" readonly value="0" />
                </div>
            </div>
            <hr>
            <div class="row justify-content-center mt-3 mb-5">
                <div class="col-10">
                    <div id="grid"></div>
                    <input id="data" name="data" type="hidden"/>
                </div>
            </div>
            <div class="row justify-content-center mt-3 mb-5">
                <div class="col-1">
                    <button id="guardar" type="submit" class="btn btn-danger" >
                        <i class="far fa-save"></i> Guardar
                    </button>
                </div>
                <div class="col-1 text-right">
                    <a href="{{ path('facturas_detalle',{'facId': detalle.facturas.id, 'fecDesde': fecDesde, 'fecHasta': fecHasta}) }}" onclick="$('#procesando').modal('show');">
                        <button id="volver" type="button" class="btn btn-warning" >
                            <i class="fas fa-undo-alt"></i> Volver
                        </button>
                    </a>
                </div>
            </div>
        </form>
    </div>
    </main>
    <!-- Modal -->
    <div class="modal fade" id="procesando" tabindex="-1" role="dialog" aria-labelledby="procesando" aria-hidden="true" data-backdrop="static" data-keyboard="false">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-body p-5">
                    <button class="btn btn-warning w-100 text-danger" type="button" disabled style="opacity: 1; color: red !important; font-size: 16px">
                        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                        <span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span>
                        Procesando...
                    </button>
                </div>

            </div>
        </div>
    </div>
    <script>
        var registros = {{ registros|json_encode|raw }};
        var detalle = {{ detalle|json_encode|raw }};
        console.log(detalle);
        $(document).ready(function () {
            var source =
                {
                    localdata: registros,
                    datafields:
                        [
                            { name: 'id', type: 'string' },
                            { name: 'disNumLote', type: 'string' },
                            { name: 'codigo_gar', type: 'string' },
                            { name: 'modelo', type: 'string' },
                            { name: 'racDescripcion', type: 'string' },
                            { name: 'secNombre', type: 'string' },
                            { name: 'palDescripcion', type: 'string' }
                        ],
                    datatype: "array",
                    pagesize: 20,
                };

            var dataAdapter = new $.jqx.dataAdapter(source);
            $("#grid").jqxGrid(
                {
                    width: '100%',
                    source: dataAdapter,
                    sortable: true,
                    showfilterrow: true,
                    filterable: true,
                    pageable: true,
                    autoheight: true,
                    rowsheight: 30,
                    editable: false,
                    localization: getLocalization('{% trans %} es {% endtrans %}'),
                    theme: '{{ theme }}',
                    selectionmode: 'checkbox',
                    columns: [
                        { text: '{% trans %}id{% endtrans %}', columntype: 'textbox', filtertype: 'textbox', datafield: 'id', width: '5%', hidden: true },
                        { text: '{% trans %}Número de lote{% endtrans %}', columntype: 'textbox', filtertype: 'checkedlist', datafield: 'disNumLote', width: '15%', hidden: true },
                        { text: '{% trans %}Rack{% endtrans %}',  columntype: 'textbox', filtertype: 'checkedlist', datafield: 'racDescripcion', width: '22%' },
                        { text: '{% trans %}Sección{% endtrans %}',  columntype: 'textbox', filtertype: 'checkedlist', datafield: 'secNombre', width: '15%', hidden: true },
                        { text: '{% trans %}Palet{% endtrans %}', columntype: 'textbox', filtertype: 'checkedlist', datafield: 'palDescripcion', width: '25%' },
                        { text: '{% trans %}Modelo{% endtrans %}', columntype: 'textbox', filtertype: 'checkedlist', datafield: 'modelo', width: '25%' },
                        { text: '{% trans %}Código de Garantia{% endtrans %}', columntype: 'textbox', filtertype: 'textbox', datafield: 'codigo_gar', width: '25%' },
                    ]
                });
            $("span:contains('www.jqwidgets.com')").hide();

            $('#grid').on('rowselect rowunselect', function (event)
            {
                // event arguments.
                var args = event.args;
                // row's bound index.
                var rowBoundIndex = args.rowindex;
                // row's data. The row's data object or null(when all rows are being selected or unselected with a single action). If you have a datafield called "firstName", to access the row's firstName, use var firstName = rowData.firstName;
                var rowData = args.row;
                var selectedrowindexes = $('#grid').jqxGrid('selectedrowindexes');
                $("#canSeleccionada").val(parseInt(selectedrowindexes.length));
                if($("#canSeleccionada").val() > parseInt($("#canRequerida").val())){
                    $("#canSeleccionada").attr('style', 'border-color: red !important; -webkit-text-fill-color: red !important');
                    //$('#grid').jqxGrid('unselectrow', rowBoundIndex);
                    //alert("Cantidad máxima requerida ya ha sido seleccionada!");
                }else{
                    $("#canSeleccionada").removeAttr('style', 'border-color: red !important; -webkit-text-fill-color: red !important');
                }
            });

            $("#guardar").click(function () {

                var rowindexes = $('#grid').jqxGrid('getselectedrowindexes');

                if(rowindexes.length < 1){
                    alert("Debe seleccionar los registros para completar la cantidad Requerida!");
                    return false;
                }
                if($("#canSeleccionada").val() > parseInt($("#canRequerida").val())){
                    alert("La cantidad seleccionada es mayor a la cantidad requerida!");
                    return false;
                }
                $('#procesando').modal('show');
                var data = [];
                rowindexes.forEach(function(currentValue, index, arr){
                    data.push($('#grid').jqxGrid('getrowdata', currentValue));
                })
                $("#data").val(JSON.stringify(data));

                /*myTimeout = setTimeout(function (){
                    alert("Factura guardada correctamente");
                    $("#volver").click();
                }, 1000);*/

            });
        });

    </script>
{% endblock %}

templates/distribucion/edit.html.twig
{% extends '../base_bk.html.twig' %}

{% block title %}Edit Distribucion{% endblock %}

{% block body %}
    <h1>Edit Distribucion</h1>

    {{ include('distribucion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('distribucion_index') }}">back to list</a>

    {{ include('distribucion/_delete_form.html.twig') }}
{% endblock %}

templates/distribucion/index.html.twig
{% extends '../base_bk.html.twig' %}

{% block title %}Distribucion index{% endblock %}

{% block body %}
    <h1>Distribucion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>DisNumLote</th>
                <th>Codigo_gar</th>
                <th>DisFecDistribucion</th>
                <th>DisFecDespacho</th>
                <th>DisEstado</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for distribucion in distribucions %}
            <tr>
                <td>{{ distribucion.id }}</td>
                <td>{{ distribucion.disNumLote }}</td>
                <td>{{ distribucion.codigoGar }}</td>
                <td>{{ distribucion.disFecDistribucion ? distribucion.disFecDistribucion|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ distribucion.disFecDespacho ? distribucion.disFecDespacho|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ distribucion.disEstado }}</td>
                <td>
                    <a href="{{ path('distribucion_show', {'id': distribucion.id}) }}">show</a>
                    <a href="{{ path('distribucion_edit', {'id': distribucion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('distribucion_new') }}">Create new</a>
{% endblock %}

templates/distribucion/new.html.twig
{% extends '../base_bk.html.twig' %}

{% block title %}New Distribucion{% endblock %}

{% block body %}
    <h1>Create new Distribucion</h1>

    {{ include('distribucion/_form.html.twig') }}

    <a href="{{ path('distribucion_index') }}">back to list</a>
{% endblock %}

templates/distribucion/show.html.twig
{% extends '../base_bk.html.twig' %}

{% block title %}Distribucion{% endblock %}

{% block body %}
    <h1>Distribucion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ distribucion.id }}</td>
            </tr>
            <tr>
                <th>DisNumLote</th>
                <td>{{ distribucion.disNumLote }}</td>
            </tr>
            <tr>
                <th>Codigo_gar</th>
                <td>{{ distribucion.codigoGar }}</td>
            </tr>
            <tr>
                <th>DisFecDistribucion</th>
                <td>{{ distribucion.disFecDistribucion ? distribucion.disFecDistribucion|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DisFecDespacho</th>
                <td>{{ distribucion.disFecDespacho ? distribucion.disFecDespacho|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>DisEstado</th>
                <td>{{ distribucion.disEstado }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('distribucion_index') }}">back to list</a>

    <a href="{{ path('distribucion_edit', {'id': distribucion.id}) }}">edit</a>

    {{ include('distribucion/_delete_form.html.twig') }}
{% endblock %}